#!/bin/sh

set -e

USER=pyth0n
export HOME=/home/$USER
if [ ! $DISPLAY ]; then
    export DISPLAY=:0
fi

. $HOME/.Xenv

# load session data

DISPER=/usr/bin/disper
STATE=$(cat /sys/bus/platform/devices/dock.0/docked)

# add docking station
if [ $STATE = '1' ]; then
    echo "add docking"
    $DISPER -e -r auto    
    echo "$DISPER -e -r auto"
fi

# remove docking station
if [ $STATE = '0' ]; then
    echo "remove remove"
    $DISPER -s -r auto    
fi



